import type { ClassSkillId, SkillCategory, SkillMechanic, UpgradeId } from "../skill-config";
import type { BalanceConfig, BotWaveSample, SkillBenchConfig } from "../balance-config";
import type { BenchmarkConfig } from "../benchmark-config";
import type { PARALLEL_BENCHMARK_RULESET, HeadlessTerminationReason, HeadlessTimeoutDiagnostic } from "../benchmark-headless";

export type PayloadId = "pierce" | "blast" | "glass" | "link";
export type ItemKind = "multiball" | "auto-barrier" | "core-repair" | "cooldown-reset";
export type BrickKind = "normal" | "boss-armor" | "boss-core" | "boss-minion";
export type BrickTrait = "standard" | "guard" | "explosive" | "indestructible" | "healer" | "reflector";
export type BossRewardId = UpgradeId;
export type BotPolicy = "balanced" | "survival" | "random";
export type BotSpeed = 1 | 2 | 4 | 8;
export type BenchmarkRunMode = "parallel" | "watch";
export type BotMetrics = { maxBalls: number; ballLosses: number; missileActivations: number; safetySaves: number; gravityRescues: number };
export type SkillBenchVariant = { batchId: string; environment: SkillBenchConfig["environment"]; skillId: UpgradeId | "original"; level: 0 | 1 | 2 | 3; skillValues: [number, number, number]; seed: number };
export type SkillSelectionSource = "start" | "wave" | "boss";
export type SkillSelectionEvent = { wave: number; skillId: UpgradeId; level: number; source: SkillSelectionSource };
export type SkillRunMetric = { activations: number; damage: number; kills: number };
export type BenchmarkRuleset = "live-v1" | "live-v2" | "watch-v1" | "parallel-v1" | typeof PARALLEL_BENCHMARK_RULESET;

export type BotRunResult = BotMetrics & {
  id: string;
  run: number;
  seed?: number;
  policy: BotPolicy;
  policyVersion?: string;
  engineVersion?: string;
  engineParity?: string;
  speed: BotSpeed;
  elapsed: number;
  wave: number;
  score: number;
  bricks: number;
  maxCombo: number;
  coreHp: number;
  upgrades: UpgradeId[];
  startingSkills: UpgradeId[];
  skillHistory: SkillSelectionEvent[];
  bossEnhancements?: Partial<Record<UpgradeId, number>>;
  skillMetrics: Partial<Record<UpgradeId, SkillRunMetric>>;
  createdAt: number;
  balanceConfig: BalanceConfig;
  benchmarkConfig: BenchmarkConfig | null;
  benchmarkRuleset?: BenchmarkRuleset | null;
  waveSamples: BotWaveSample[];
  evaluationComplete: boolean;
  terminationReason?: HeadlessTerminationReason;
  timeoutDiagnostic?: HeadlessTimeoutDiagnostic | null;
  skillBench: SkillBenchVariant | null;
};

export type Upgrade = {
  id: UpgradeId;
  name: string;
  category: SkillCategory;
  mechanic: SkillMechanic;
  tag: string;
  description: string;
  color: string;
};

export type UpgradeChoice = { upgrade: Upgrade; ballCost: 0 | 1 | 2 };

export type GhostRecord = {
  id: string;
  name: string;
  score: number;
  bricks: number;
  maxCombo: number;
  upgrades: UpgradeId[];
  skillHistory: SkillSelectionEvent[];
  skillMetrics: Partial<Record<UpgradeId, SkillRunMetric>>;
  paddleTrack: number[];
  createdAt: number;
};

export type Ball = {
  x: number;
  y: number;
  vx: number;
  vy: number;
  radius: number;
  owner: "player" | "ghost";
  ghostIndex?: number;
  pierce: number;
  maxPierce: number;
  blast: number;
  payload: PayloadId | null;
  payloadLevel: number;
  payloads: Partial<Record<PayloadId, number>>;
  attackPower: number;
  color: string;
  sourcePaddleId: string;
  missileTime: number;
  missileHitCooldown: number;
  gravityRescueCooldown: number;
  gravityBaseSpeed: number | null;
  explosionBaseSpeed: number | null;
  explosionBoostRatio: number;
  explosionBoostTime: number;
  canTriggerSkills: boolean;
  skillGeneration: number;
  skillCharges: Partial<Record<ClassSkillId, number>>;
  skillCooldowns: Partial<Record<ClassSkillId, number>>;
  visualSkill: ClassSkillId | null;
  temporaryTime: number;
  waveBonus: boolean;
  respawnRecoveryTime: number;
  respawnRecoveryDuration: number;
  respawnRecoveryBaseSpeed: number;
};

export type Brick = {
  x: number;
  y: number;
  w: number;
  h: number;
  hp: number;
  maxHp: number;
  hue: number;
  alive: boolean;
  drop: ItemKind | null;
  kind: BrickKind;
  trait: BrickTrait;
  guardReady: boolean;
  healTimer: number;
  poisonTime: number;
  poisonTick: number;
  poisonSourcePaddleId: string | null;
  burnTime: number;
  burnTick: number;
  burnLevel: number;
  burnSourcePaddleId: string | null;
  healBlockTime: number;
  blastVulnerability: number;
  blastVulnerabilitySourcePaddleId: string | null;
  frostVulnerability: number;
  traitLockTime: number;
  lastHitPaddleId: string | null;
};

export type DropItem = {
  id: number;
  x: number;
  y: number;
  vy: number;
  alive: boolean;
  kind: ItemKind;
};

export type SafetyBlock = { ownerPaddleId: string; x: number; y: number; width: number; color: string };
export type GravityWell = { ownerPaddleId: string; x: number; y: number; radius: number; life: number; maxLife: number; color: string; damagePerSecond: number; damageTick: number };
export type Particle = { x: number; y: number; vx: number; vy: number; life: number; color: string };
export type Flash = { text: string; x: number; y: number; life: number; color: string; emphasis?: "damage" };
export type GameEffect = { kind: "ring" | "beam" | "blast" | "drop" | "spark" | "lightning" | "skill"; x: number; y: number; x2: number; y2: number; size: number; life: number; maxLife: number; color: string; variant: number; skillId: ClassSkillId | null };
export type PaddleCounter = { reflections: number; barrierReflections: number; missileReflections: number; safetyTimer: number; gravityTimer: number; directKills: number; pierceKills: number; feverMilestone: number; lastShotTimer: number; combo: number; comboTimer: number; skillCooldowns: Partial<Record<ClassSkillId, number>>; skillReflections?: Partial<Record<ClassSkillId, number>>; chargePulse?: number; chargeColor?: string };

export type GameState = {
  balls: Ball[];
  bricks: Brick[];
  paddleX: number;
  paddleWidth: number;
  ghostPaddles: number[];
  elapsed: number;
  score: number;
  level: number;
  combo: number;
  maxCombo: number;
  comboTimer: number;
  bricksBroken: number;
  upgrades: UpgradeId[];
  skillHistory: SkillSelectionEvent[];
  skillMetrics: Partial<Record<UpgradeId, SkillRunMetric>>;
  paddleTrack: number[];
  particles: Particle[];
  particlePool: Particle[];
  particlePoolCursor: number;
  flashes: Flash[];
  effects: GameEffect[];
  effectPool: GameEffect[];
  effectPoolCursor: number;
  items: DropItem[];
  safetyBlocks: SafetyBlock[];
  gravityWells: GravityWell[];
  paddleBarriers: Record<string, number>;
  itemBarrierTime: number;
  paddleCounters: Record<string, PaddleCounter>;
  coreHp: number;
  maxCoreHp: number;
  bossActive: boolean;
  bossPending: boolean;
  bossStage: number;
  nextBossWave: number;
  bossTimeRemaining: number;
  bossSkillTimer: number;
  bossAttackPattern: number;
  bossMultiballsRemaining: number;
  bossRewards: BossRewardId[];
  bossEnhancements: Partial<Record<UpgradeId, number>>;
  autoGuard: boolean;
  rowTimer: number;
  rowInterval: number;
  overdriveLevel: number;
  shakeStrength: number;
  shakeTime: number;
  shakeDuration: number;
  screenFlashColor: string;
  screenFlashTime: number;
  screenFlashDuration: number;
  coreBreakTime: number;
  coreBreakDuration: number;
  coreBreakX: number;
  coreBreakY: number;
  wave: number;
  pendingWave: number | null;
  failed: boolean;
  failureReason: "ball" | "core" | null;
  /** Set only by the opt-in canonical bridge when its target wave completes. */
  canonicalComplete?: boolean;
  botMetrics: BotMetrics;
  botWaveSamples: BotWaveSample[];
  botSampleKey: string;
};
